"""
Curriculum resource catalog for overnight ingestion.

Each entry describes one document to download and ingest into hs_curriculum.
Fields:
  slug/title   — identifier used to construct download URL or log progress
  subject      — canonical subject name (must match context_store._SUBJECT_ALIASES)
  grade_level  — "GCSE", "A-Level", "AP", "Grade 9-12", "College", etc.
  curriculum   — "us" | "uk"
  source_type  — "openstax" | "gcse_aqa" | "direct"
  source_name  — human-readable source label
  license      — license string
  page_url     — the human-readable page (used as reference)
  direct_url   — direct PDF download URL (leave "" to scrape page_url)
"""

# ── US OpenStax ──────────────────────────────────────────────────────────────

OPENSTAX_BOOKS: list[dict] = [
    # ── Already ingested / verified URLs ─────────────────────────────────────
    {
        "slug": "biology-2e",
        "title": "Biology 2e",
        "subject": "Biology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/biology-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf",
    },
    {
        "slug": "chemistry-2e",
        "title": "Chemistry 2e",
        "subject": "Chemistry",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/chemistry-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Chemistry2e-WEB.pdf",
    },
    {
        "slug": "college-algebra-2e",
        "title": "College Algebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Stitz-Zeager Open Source Mathematics",
        "license": "CC-BY-NC-SA 3.0",
        "page_url": "http://www.stitz-zeager.com/college_algebra.html",
        "direct_url": "http://www.stitz-zeager.com/szca07042013.pdf",
    },
    {
        "slug": "calculus-volume-1",
        "title": "Calculus Volume 1",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://archive.org/details/calculus-volume-1",
        "direct_url": "https://archive.org/download/calculus-volume-1/Calculus%2C%20Volume%201.pdf",
    },
    {
        "slug": "calculus-volume-2",
        "title": "Calculus Volume 2",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://archive.org/details/calculus-volume-2-web",
        "direct_url": "https://archive.org/download/calculus-volume-2-web/Calculus_Volume_2_-_WEB.pdf",
    },
    {
        "slug": "introductory-statistics",
        "title": "Introductory Statistics",
        "subject": "Statistics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introductory-statistics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Statistics-WEB.pdf",
    },
    {
        "slug": "psychology-2e",
        "title": "Introduction to Psychology",
        "subject": "Psychology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/introductiontopsychology/",
        "direct_url": "https://opentextbc.ca/introductiontopsychology/open/download?type=pdf",
    },

    # ── Fixed: were failing with bad/missing URLs ─────────────────────────────
    {
        "slug": "algebra-and-trigonometry-2e",
        "title": "Algebra and Trigonometry 2e",
        "subject": "Algebra",
        "grade_level": "Grade 10-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/algebra-and-trigonometry-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AlgebraAndTrigonometry2e-WEB_EBPcvmG.pdf",
    },
    {
        "slug": "precalculus-2e",
        "title": "Precalculus 2e",
        "subject": "Pre-Calculus",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/precalculus-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Precalculus2e-WEB_rNsEQ3h.pdf",
    },
    {
        "slug": "us-history",
        "title": "U.S. History",
        "subject": "US History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/us-history",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/USHistory-WEB.pdf",
    },
    {
        "slug": "world-history-volume-1",
        "title": "World History Volume 1",
        "subject": "World History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/world-history-volume-1",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/WorldHistoryVolume1-WEB.pdf",
    },
    {
        "slug": "world-history-volume-2",
        "title": "World History Volume 2",
        "subject": "World History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/world-history-volume-2",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/WorldHistoryVolume2-WEB.pdf",
    },
    {
        "slug": "sociology-3e",
        "title": "Introduction to Sociology 3e",
        "subject": "Sociology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-sociology-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionToSociology3e-WEB.pdf",
    },
    {
        "slug": "principles-economics-3e",
        "title": "Principles of Economics 3e",
        "subject": "Economics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-economics-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfEconomics3e-WEB.pdf",
    },
    {
        "slug": "anatomy-and-physiology",
        "title": "Anatomy and Physiology",
        "subject": "Anatomy",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/anatomy-and-physiology",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AnatomyandPhysiology-WEB.pdf",
    },
    {
        "slug": "college-physics-2e",
        "title": "College Physics 2e",
        "subject": "Physics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/college-physics-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/College_Physics_2e-WEB.pdf",
    },

    # ── New: College Freshman ─────────────────────────────────────────────────
    {
        "slug": "university-physics-volume-1",
        "title": "University Physics Volume 1",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/university-physics-volume-1",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume1-WEB.pdf",
    },
    {
        "slug": "university-physics-volume-2",
        "title": "University Physics Volume 2",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/university-physics-volume-2",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume2-WEB.pdf",
    },
    {
        "slug": "university-physics-volume-3",
        "title": "University Physics Volume 3",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/university-physics-volume-3",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume3-WEB.pdf",
    },
    {
        "slug": "calculus-volume-3",
        "title": "Calculus Volume 3",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/calculus-volume-3",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/CalculusVolume3-WEB.pdf",
    },
    {
        "slug": "microbiology",
        "title": "Microbiology",
        "subject": "Biology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/microbiology",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Microbiology-WEB.pdf",
    },
    {
        "slug": "astronomy-2e",
        "title": "Astronomy 2e",
        "subject": "Astronomy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/astronomy-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Astronomy2e-WEB.pdf",
    },
    {
        "slug": "american-government-3e",
        "title": "American Government 3e",
        "subject": "US History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/american-government-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AmericanGovernment3e-WEB.pdf",
    },
    {
        "slug": "introduction-to-philosophy",
        "title": "Introduction to Philosophy",
        "subject": "Philosophy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-philosophy",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionToPhilosophy-WEB.pdf",
    },
    {
        "slug": "concepts-of-biology",
        "title": "Concepts of Biology",
        "subject": "Biology",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/concepts-biology",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsOfBiology-WEB.pdf",
    },
    {
        "slug": "prealgebra-2e",
        "title": "Prealgebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/prealgebra-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Prealgebra2e-WEB.pdf",
    },
    {
        "slug": "chemistry-atoms-first-2e",
        "title": "Chemistry: Atoms First 2e",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/chemistry-atoms-first-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ChemistryAtomsFirst2e-WEB.pdf",
    },
    {
        "slug": "principles-microeconomics-3e",
        "title": "Principles of Microeconomics 3e",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-microeconomics-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfMicroeconomics3e-WEB.pdf",
    },
    {
        "slug": "principles-macroeconomics-3e",
        "title": "Principles of Macroeconomics 3e",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-macroeconomics-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfMacroeconomics3e-WEB.pdf",
    },
    {
        "slug": "introductory-business-statistics",
        "title": "Introductory Business Statistics",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introductory-business-statistics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductoryBusinessStatistics-WEB.pdf",
    },
    {
        "slug": "statistics-hs",
        "title": "Statistics (High School)",
        "subject": "Statistics",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/statistics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Statistics-WEB.pdf",
    },
    {
        "slug": "introduction-to-sociology-2e",
        "title": "Introduction to Sociology 2e",
        "subject": "Sociology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/introductiontosociology2ndedition/",
        "direct_url": "https://opentextbc.ca/introductiontosociology2ndedition/open/download?type=pdf",
    },
    {
        "slug": "business-ethics",
        "title": "Business Ethics",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/business-ethics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/BusinessEthics-WEB.pdf",
    },
    {
        "slug": "introduction-business-2e",
        "title": "Introduction to Business",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-business",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionToBusiness-WEB.pdf",
    },
    {
        "slug": "writing-guide",
        "title": "Writing Guide with Handbook",
        "subject": "English",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/writing-guide",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/WritingGuide-WEB.pdf",
    },
    {
        "slug": "contemporary-mathematics",
        "title": "Contemporary Mathematics",
        "subject": "Algebra",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/contemporary-mathematics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ContemporaryMathematics-WEB.pdf",
    },
    {
        "slug": "linear-algebra",
        "title": "A First Course in Linear Algebra",
        "subject": "Algebra",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Robert A. Beezer / GFDL",
        "license": "GFDL",
        "page_url": "http://linear.pugetsound.edu/",
        "direct_url": "http://linear.pugetsound.edu/download/fcla-electric-2.22.pdf",
    },
    {
        "slug": "differential-equations",
        "title": "Elementary Differential Equations",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "William Trench / CC-BY-NC-SA",
        "license": "CC-BY-NC-SA",
        "page_url": "https://digitalcommons.trinity.edu/mono/8/",
        "direct_url": "https://digitalcommons.trinity.edu/cgi/viewcontent.cgi?article=1008&context=mono",
    },
    {
        "slug": "discrete-mathematics",
        "title": "Discrete Mathematics: An Open Introduction",
        "subject": "Mathematics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Oscar Levin / CC-BY-SA",
        "license": "CC-BY-SA 4.0",
        "page_url": "https://discrete.openmathbooks.org/dmoi3.html",
        "direct_url": "https://discrete.openmathbooks.org/pdfs/dmoi3-tablet.pdf",
    },
    {
        "slug": "organic-chemistry-clayden",
        "title": "Organic Chemistry (Free Edition)",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "LibreTexts",
        "license": "CC-BY-NC-SA",
        "page_url": "https://chem.libretexts.org/Bookshelves/Organic_Chemistry",
        "direct_url": "https://batch.libretexts.org/print/Finished/chem-24911/Full.pdf",
    },
    {
        "slug": "general-chemistry-libretexts",
        "title": "General Chemistry: Principles, Patterns, and Applications",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "LibreTexts",
        "license": "CC-BY-NC-SA",
        "page_url": "https://chem.libretexts.org/Bookshelves/General_Chemistry",
        "direct_url": "https://batch.libretexts.org/print/Finished/chem-21547/Full.pdf",
    },
    {
        "slug": "intro-computer-science",
        "title": "Think Python 3e",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / CC-BY-NC",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-python-3rd-edition/",
        "direct_url": "https://greenteapress.com/thinkpython/thinkpython.pdf",
    },
    {
        "slug": "think-stats",
        "title": "Think Stats: Probability and Statistics for Programmers",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / CC-BY-NC",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-stats-2e/",
        "direct_url": "https://greenteapress.com/thinkstats2/thinkstats2.pdf",
    },
]

# ── UK AQA GCSE ──────────────────────────────────────────────────────────────

AQA_GCSE_RESOURCES: list[dict] = [
    {
        "slug": "aqa-gcse-biology-8461",
        "title": "AQA GCSE Biology Specification",
        "subject": "Biology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/biology/gcse/biology-8461/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-chemistry-8462",
        "title": "AQA GCSE Chemistry Specification",
        "subject": "Chemistry",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/chemistry/gcse/chemistry-8462/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-physics-8463",
        "title": "AQA GCSE Physics Specification",
        "subject": "Physics",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/physics/gcse/physics-8463/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-maths-8300",
        "title": "AQA GCSE Mathematics Specification",
        "subject": "Algebra",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-english-language-8700",
        "title": "AQA GCSE English Language Specification",
        "subject": "English",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/gcse/english-language-8700/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-english-literature-8702",
        "title": "AQA GCSE English Literature Specification",
        "subject": "English",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-geography-8035",
        "title": "AQA GCSE Geography Specification",
        "subject": "Earth Science",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-history-8145",
        "title": "AQA GCSE History Specification",
        "subject": "History",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/history/gcse/history-8145/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-economics-8136",
        "title": "AQA GCSE Economics Specification",
        "subject": "Economics",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/economics/gcse/economics-8136/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-psychology-8182",
        "title": "AQA GCSE Psychology Specification",
        "subject": "Psychology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/psychology/gcse/psychology-8182/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-computer-science-8525",
        "title": "AQA GCSE Computer Science Specification",
        "subject": "Computer Science",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/computer-science-and-it/gcse/computer-science-8525/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-religious-studies-8062",
        "title": "AQA GCSE Religious Studies Specification",
        "subject": "Religious Studies",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/religious-studies/gcse/religious-studies-a-8062/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-sociology-8192",
        "title": "AQA GCSE Sociology Specification",
        "subject": "Sociology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-french-8658",
        "title": "AQA GCSE French Specification",
        "subject": "French",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/languages/gcse/french-8658/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-spanish-8698",
        "title": "AQA GCSE Spanish Specification",
        "subject": "Spanish",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/languages/gcse/spanish-8698/specification",
        "direct_url": "",
    },
]

# ── UK AQA A-Level ───────────────────────────────────────────────────────────

AQA_ALEVEL_RESOURCES: list[dict] = [
    {
        "slug": "aqa-alevel-biology-7402",
        "title": "AQA A-Level Biology Specification",
        "subject": "Biology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/biology/as-and-a-level/biology-7401-7402/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-chemistry-7405",
        "title": "AQA A-Level Chemistry Specification",
        "subject": "Chemistry",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/chemistry/as-and-a-level/chemistry-7404-7405/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-physics-7408",
        "title": "AQA A-Level Physics Specification",
        "subject": "Physics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/physics/as-and-a-level/physics-7407-7408/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-maths-7357",
        "title": "AQA A-Level Mathematics Specification",
        "subject": "Calculus",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/as-and-a-level/mathematics-7357/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-further-maths-7367",
        "title": "AQA A-Level Further Mathematics Specification",
        "subject": "Calculus",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/as-and-a-level/further-mathematics-7367/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-economics-7136",
        "title": "AQA A-Level Economics Specification",
        "subject": "Economics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/economics/as-and-a-level/economics-7135-7136/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-psychology-7182",
        "title": "AQA A-Level Psychology Specification",
        "subject": "Psychology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/psychology/as-and-a-level/psychology-7181-7182/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-computer-science-7517",
        "title": "AQA A-Level Computer Science Specification",
        "subject": "Computer Science",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/computer-science-and-it/as-and-a-level/computer-science-7516-7517/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-history-7042",
        "title": "AQA A-Level History Specification",
        "subject": "History",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/history/as-and-a-level/history-7041-7042/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-geography-7037",
        "title": "AQA A-Level Geography Specification",
        "subject": "Earth Science",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/geography/as-and-a-level/geography-7036-7037/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-sociology-7192",
        "title": "AQA A-Level Sociology Specification",
        "subject": "Sociology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/sociology/as-and-a-level/sociology-7191-7192/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-english-literature-7712",
        "title": "AQA A-Level English Literature Specification",
        "subject": "English",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/as-and-a-level/english-literature-a-7711-7712/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-business-7132",
        "title": "AQA A-Level Business Specification",
        "subject": "Economics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/business/as-and-a-level/business-7131-7132/specification",
        "direct_url": "",
    },
]

ALL_SOURCES: list[dict] = OPENSTAX_BOOKS + AQA_GCSE_RESOURCES + AQA_ALEVEL_RESOURCES

SOURCE_FILTER: dict[str, list[dict]] = {
    "openstax": OPENSTAX_BOOKS,
    "gcse": AQA_GCSE_RESOURCES,
    "alevel": AQA_ALEVEL_RESOURCES,
    "uk": AQA_GCSE_RESOURCES + AQA_ALEVEL_RESOURCES,
    "us": OPENSTAX_BOOKS,
    "all": ALL_SOURCES,
}
