"""
Curriculum resource catalog for overnight ingestion.

Each entry describes one document to download and ingest into hs_curriculum.
Fields:
  slug/title   — identifier used to construct download URL or log progress
  subject      — canonical subject name (must match context_store._SUBJECT_ALIASES)
  grade_level  — "GCSE", "A-Level", "AP", "Grade 9-12", "College", etc.
  curriculum   — "us" | "uk"
  source_type  — "openstax" | "gcse_aqa" | "direct"
  source_name  — human-readable source label
  license      — license string
  page_url     — the human-readable page (used as reference)
  direct_url   — direct PDF download URL (leave "" to scrape page_url)
"""

# ── US OpenStax ──────────────────────────────────────────────────────────────

OPENSTAX_BOOKS: list[dict] = [
    # ── Already ingested / verified URLs ─────────────────────────────────────
    {
        "slug": "biology-2e",
        "title": "Biology 2e",
        "subject": "Biology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/biology-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf",
    },
    {
        "slug": "chemistry-2e",
        "title": "Chemistry 2e",
        "subject": "Chemistry",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/chemistry-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Chemistry2e-WEB.pdf",
    },
    {
        "slug": "college-algebra-2e",
        "title": "College Algebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Stitz-Zeager Open Source Mathematics",
        "license": "CC-BY-NC-SA 3.0",
        "page_url": "http://www.stitz-zeager.com/college_algebra.html",
        "direct_url": "http://www.stitz-zeager.com/szca07042013.pdf",
    },
    {
        "slug": "calculus-volume-1",
        "title": "Calculus Volume 1",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://archive.org/details/calculus-volume-1",
        "direct_url": "https://archive.org/download/calculus-volume-1/Calculus%2C%20Volume%201.pdf",
    },
    {
        "slug": "calculus-volume-2",
        "title": "Calculus Volume 2",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://archive.org/details/calculus-volume-2-web",
        "direct_url": "https://archive.org/download/calculus-volume-2-web/Calculus_Volume_2_-_WEB.pdf",
    },
    {
        "slug": "introductory-statistics",
        "title": "Introductory Statistics",
        "subject": "Statistics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introductory-statistics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Statistics-WEB.pdf",
    },
    {
        "slug": "psychology-2e",
        "title": "Introduction to Psychology",
        "subject": "Psychology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/introductiontopsychology/",
        "direct_url": "https://opentextbc.ca/introductiontopsychology/open/download?type=pdf",
    },

    # ── Fixed: were failing with bad/missing URLs ─────────────────────────────
    {
        "slug": "algebra-and-trigonometry-2e",
        "title": "Algebra and Trigonometry 2e",
        "subject": "Algebra",
        "grade_level": "Grade 10-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/algebra-and-trigonometry-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AlgebraAndTrigonometry2e-WEB_EBPcvmG.pdf",
    },
    {
        "slug": "precalculus-2e",
        "title": "Precalculus 2e",
        "subject": "Pre-Calculus",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/precalculus-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Precalculus2e-WEB_rNsEQ3h.pdf",
    },
    {
        "slug": "us-history",
        "title": "U.S. History",
        "subject": "US History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/us-history",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/USHistory-WEB.pdf",
    },
    {
        "slug": "world-history-volume-1",
        "title": "World History Volume 1",
        "subject": "World History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/world-history-volume-1",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/WorldHistoryVolume1-WEB.pdf",
    },
    {
        "slug": "world-history-volume-2",
        "title": "World History Volume 2",
        "subject": "World History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/world-history-volume-2",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/WorldHistoryVolume2-WEB.pdf",
    },
    {
        "slug": "sociology-3e",
        "title": "Introduction to Sociology 3e",
        "subject": "Sociology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-sociology-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionToSociology3e-WEB.pdf",
    },
    {
        "slug": "principles-economics-3e",
        "title": "Principles of Economics 3e",
        "subject": "Economics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-economics-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfEconomics3e-WEB.pdf",
    },
    {
        "slug": "anatomy-and-physiology",
        "title": "Anatomy and Physiology",
        "subject": "Anatomy",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/anatomy-and-physiology",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AnatomyandPhysiology-WEB.pdf",
    },
    {
        "slug": "college-physics-2e",
        "title": "College Physics 2e",
        "subject": "Physics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/college-physics-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/College_Physics_2e-WEB.pdf",
    },

    # ── New: College Freshman ─────────────────────────────────────────────────
    {
        "slug": "university-physics-volume-1",
        "title": "University Physics Volume 1",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/university-physics-volume-1",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume1-WEB.pdf",
    },
    {
        "slug": "university-physics-volume-2",
        "title": "University Physics Volume 2",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/university-physics-volume-2",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume2-WEB.pdf",
    },
    {
        "slug": "university-physics-volume-3",
        "title": "University Physics Volume 3",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/university-physics-volume-3",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/UniversityPhysicsVolume3-WEB.pdf",
    },
    {
        "slug": "calculus-volume-3",
        "title": "Calculus Volume 3",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/calculus-volume-3",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/CalculusVolume3-WEB.pdf",
    },
    {
        "slug": "microbiology",
        "title": "Microbiology",
        "subject": "Biology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/microbiology",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Microbiology-WEB.pdf",
    },
    {
        "slug": "astronomy-2e",
        "title": "Astronomy 2e",
        "subject": "Astronomy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/astronomy-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Astronomy2e-WEB.pdf",
    },
    {
        "slug": "american-government-3e",
        "title": "American Government 3e",
        "subject": "Government",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/american-government-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AmericanGovernment3e-WEB.pdf",
    },
    {
        "slug": "introduction-to-philosophy",
        "title": "Introduction to Philosophy",
        "subject": "Philosophy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-philosophy",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionToPhilosophy-WEB.pdf",
    },
    {
        "slug": "concepts-of-biology",
        "title": "Concepts of Biology",
        "subject": "Biology",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/concepts-biology",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ConceptsOfBiology-WEB.pdf",
    },
    {
        "slug": "prealgebra-2e",
        "title": "Prealgebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/prealgebra-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Prealgebra2e-WEB.pdf",
    },
    {
        "slug": "chemistry-atoms-first-2e",
        "title": "Chemistry: Atoms First 2e",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/chemistry-atoms-first-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ChemistryAtomsFirst2e-WEB.pdf",
    },
    {
        "slug": "principles-microeconomics-3e",
        "title": "Principles of Microeconomics 3e",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-microeconomics-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfMicroeconomics3e-WEB.pdf",
    },
    {
        "slug": "principles-macroeconomics-3e",
        "title": "Principles of Macroeconomics 3e",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-macroeconomics-3e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfMacroeconomics3e-WEB.pdf",
    },
    {
        "slug": "introductory-business-statistics",
        "title": "Introductory Business Statistics",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introductory-business-statistics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductoryBusinessStatistics-WEB.pdf",
    },
    {
        "slug": "statistics-hs",
        "title": "Statistics (High School)",
        "subject": "Statistics",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/statistics",
        "direct_url": "",
    },
    {
        "slug": "introduction-to-sociology-2e",
        "title": "Introduction to Sociology 2e",
        "subject": "Sociology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/introductiontosociology2ndedition/",
        "direct_url": "https://opentextbc.ca/introductiontosociology2ndedition/open/download?type=pdf",
    },
    {
        "slug": "business-ethics",
        "title": "Business Ethics",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/business-ethics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/BusinessEthics-WEB.pdf",
    },
    {
        "slug": "introduction-business-2e",
        "title": "Introduction to Business",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-business",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntroductionToBusiness-WEB.pdf",
    },
    {
        "slug": "writing-guide",
        "title": "Writing Guide with Handbook",
        "subject": "English",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/writing-guide",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/WritingGuide-WEB.pdf",
    },
    {
        "slug": "contemporary-mathematics",
        "title": "Contemporary Mathematics",
        "subject": "Algebra",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/contemporary-mathematics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ContemporaryMathematics-WEB.pdf",
    },
    {
        "slug": "linear-algebra",
        "title": "A First Course in Linear Algebra",
        "subject": "Algebra",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Robert A. Beezer / GFDL",
        "license": "GFDL",
        "page_url": "http://linear.pugetsound.edu/",
        "direct_url": "http://linear.pugetsound.edu/download/fcla-electric-2.22.pdf",
    },
    {
        "slug": "differential-equations",
        "title": "Elementary Differential Equations",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "William Trench / CC-BY-NC-SA",
        "license": "CC-BY-NC-SA",
        "page_url": "https://digitalcommons.trinity.edu/mono/8/",
        "direct_url": "https://digitalcommons.trinity.edu/cgi/viewcontent.cgi?article=1008&context=mono",
    },
    {
        "slug": "discrete-mathematics",
        "title": "Discrete Mathematics: An Open Introduction",
        "subject": "Mathematics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Oscar Levin / CC-BY-SA",
        "license": "CC-BY-SA 4.0",
        "page_url": "https://discrete.openmathbooks.org/dmoi3.html",
        "direct_url": "https://discrete.openmathbooks.org/pdfs/dmoi3-tablet.pdf",
    },
    {
        "slug": "organic-chemistry-clayden",
        "title": "Organic Chemistry (Free Edition)",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "LibreTexts",
        "license": "CC-BY-NC-SA",
        "page_url": "https://chem.libretexts.org/Bookshelves/Organic_Chemistry",
        "direct_url": "https://batch.libretexts.org/print/Finished/chem-24911/Full.pdf",
    },
    {
        "slug": "general-chemistry-libretexts",
        "title": "General Chemistry: Principles, Patterns, and Applications",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "LibreTexts",
        "license": "CC-BY-NC-SA",
        "page_url": "https://chem.libretexts.org/Bookshelves/General_Chemistry",
        "direct_url": "https://batch.libretexts.org/print/Finished/chem-21547/Full.pdf",
    },
    {
        "slug": "intro-computer-science",
        "title": "Think Python 3e",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / CC-BY-NC",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-python-3rd-edition/",
        "direct_url": "https://greenteapress.com/thinkpython/thinkpython.pdf",
    },
    {
        "slug": "think-stats",
        "title": "Think Stats: Probability and Statistics for Programmers",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / CC-BY-NC",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-stats-2e/",
        "direct_url": "https://greenteapress.com/thinkstats2/thinkstats2.pdf",
    },

    # ── HS Math (pre-algebra to pre-calculus) ─────────────────────────────────
    {
        "slug": "elementary-algebra-2e",
        "title": "Elementary Algebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 9-10",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/elementary-algebra-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/ElementaryAlgebra2e-WEB.pdf",
    },
    {
        "slug": "intermediate-algebra-2e",
        "title": "Intermediate Algebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 10-11",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/intermediate-algebra-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/IntermediateAlgebra2e-WEB.pdf",
    },
    {
        "slug": "college-algebra-corequisite-2e",
        "title": "College Algebra with Corequisite Support 2e",
        "subject": "Algebra",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/college-algebra-corequisite-support-2e",
        "direct_url": "",
    },

    # ── College Science ────────────────────────────────────────────────────────
    {
        "slug": "anatomy-and-physiology-2e",
        "title": "Anatomy and Physiology 2e",
        "subject": "Anatomy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/anatomy-and-physiology-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AnatomyandPhysiology2e-WEB.pdf",
    },
    {
        "slug": "concepts-of-biology-hs",
        "title": "Biology for AP Courses",
        "subject": "Biology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/biology-ap-courses",
        "direct_url": "",
    },
    {
        "slug": "chemistry-hs",
        "title": "Chemistry for AP Courses 2e",
        "subject": "Chemistry",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/chemistry-ap-courses-2e",
        "direct_url": "",
    },
    {
        "slug": "physics-hs",
        "title": "Physics for AP Courses",
        "subject": "Physics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/ap-physics-collection",
        "direct_url": "",
    },
    {
        "slug": "high-school-physics",
        "title": "High School Physics",
        "subject": "Physics",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/physics",
        "direct_url": "",
    },

    # ── College Statistics ─────────────────────────────────────────────────────
    {
        "slug": "introductory-statistics-2e",
        "title": "Introductory Statistics 2e",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introductory-statistics-2e",
        "direct_url": "",
    },

    # ── Social Sciences ────────────────────────────────────────────────────────
    {
        "slug": "psychology-2e-openstax",
        "title": "Psychology 2e",
        "subject": "Psychology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/psychology-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Psychology2e-WEB.pdf",
    },
    {
        "slug": "lifespan-development",
        "title": "Lifespan Development",
        "subject": "Psychology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/lifespan-development",
        "direct_url": "",
    },
    {
        "slug": "introduction-anthropology",
        "title": "Introduction to Anthropology",
        "subject": "Sociology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-anthropology",
        "direct_url": "",
    },
    {
        "slug": "introduction-political-science",
        "title": "Introduction to Political Science",
        "subject": "Government",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introduction-political-science",
        "direct_url": "",
    },
    {
        "slug": "ethnic-studies",
        "title": "Ethnic Studies",
        "subject": "Sociology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/ethnic-studies",
        "direct_url": "",
    },

    # ── Business & Accounting ─────────────────────────────────────────────────
    {
        "slug": "principles-financial-accounting",
        "title": "Principles of Accounting Vol 1: Financial Accounting",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-financial-accounting",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfAccounting-Volume1-WEB.pdf",
    },
    {
        "slug": "principles-managerial-accounting",
        "title": "Principles of Accounting Vol 2: Managerial Accounting",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-managerial-accounting",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/PrinciplesOfAccounting-Volume2-WEB.pdf",
    },
    {
        "slug": "organizational-behavior",
        "title": "Organizational Behavior",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/organizational-behavior",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/OrganizationalBehavior-WEB.pdf",
    },
    {
        "slug": "management-2e",
        "title": "Management 2e",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/management-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Management2e-WEB.pdf",
    },
    {
        "slug": "entrepreneurship",
        "title": "Entrepreneurship",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/entrepreneurship",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Entrepreneurship-WEB.pdf",
    },
    {
        "slug": "principles-marketing",
        "title": "Principles of Marketing",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-marketing",
        "direct_url": "",
    },
    {
        "slug": "workplace-software-skills",
        "title": "Workplace Software and Skills",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/workplace-software-and-skills",
        "direct_url": "",
    },

    # ── College Success / Skills ──────────────────────────────────────────────
    {
        "slug": "college-success",
        "title": "College Success",
        "subject": "English",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/college-success",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/CollegeSuccess-WEB.pdf",
    },
    {
        "slug": "college-success-concise",
        "title": "College Success Concise",
        "subject": "English",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/college-success-concise",
        "direct_url": "",
    },

    # ── Nursing / Health ──────────────────────────────────────────────────────
    {
        "slug": "nursing-fundamentals",
        "title": "Nursing Fundamentals",
        "subject": "Anatomy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/nursing-fundamentals",
        "direct_url": "",
    },
    {
        "slug": "pharmacology",
        "title": "Pharmacology",
        "subject": "Anatomy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/pharmacology",
        "direct_url": "",
    },
    {
        "slug": "nutrition-science",
        "title": "Nutrition Science and Everyday Application",
        "subject": "Environmental Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/nutrition-science-and-everyday-application",
        "direct_url": "",
    },

]

# ── UK AQA GCSE ──────────────────────────────────────────────────────────────

AQA_GCSE_RESOURCES: list[dict] = [
    {
        "slug": "aqa-gcse-biology-8461",
        "title": "AQA GCSE Biology Specification",
        "subject": "Biology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/biology/gcse/biology-8461/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-chemistry-8462",
        "title": "AQA GCSE Chemistry Specification",
        "subject": "Chemistry",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/chemistry/gcse/chemistry-8462/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-physics-8463",
        "title": "AQA GCSE Physics Specification",
        "subject": "Physics",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/physics/gcse/physics-8463/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-maths-8300",
        "title": "AQA GCSE Mathematics Specification",
        "subject": "Algebra",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-english-language-8700",
        "title": "AQA GCSE English Language Specification",
        "subject": "English",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/gcse/english-language-8700/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-english-literature-8702",
        "title": "AQA GCSE English Literature Specification",
        "subject": "English",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-geography-8035",
        "title": "AQA GCSE Geography Specification",
        "subject": "Earth Science",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-history-8145",
        "title": "AQA GCSE History Specification",
        "subject": "History",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/history/gcse/history-8145/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-economics-8136",
        "title": "AQA GCSE Economics Specification",
        "subject": "Economics",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/economics/gcse/economics-8136/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-psychology-8182",
        "title": "AQA GCSE Psychology Specification",
        "subject": "Psychology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/psychology/gcse/psychology-8182/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-computer-science-8525",
        "title": "AQA GCSE Computer Science Specification",
        "subject": "Computer Science",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/computer-science-and-it/gcse/computer-science-8525/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-religious-studies-8062",
        "title": "AQA GCSE Religious Studies Specification",
        "subject": "Religious Studies",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/religious-studies/gcse/religious-studies-a-8062/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-sociology-8192",
        "title": "AQA GCSE Sociology Specification",
        "subject": "Sociology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/sociology/gcse/sociology-8192/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-french-8658",
        "title": "AQA GCSE French Specification",
        "subject": "French",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/languages/gcse/french-8658/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-spanish-8698",
        "title": "AQA GCSE Spanish Specification",
        "subject": "Spanish",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/languages/gcse/spanish-8698/specification",
        "direct_url": "",
    },
]

# ── UK AQA A-Level ───────────────────────────────────────────────────────────

AQA_ALEVEL_RESOURCES: list[dict] = [
    {
        "slug": "aqa-alevel-biology-7402",
        "title": "AQA A-Level Biology Specification",
        "subject": "Biology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/biology/as-and-a-level/biology-7401-7402/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-chemistry-7405",
        "title": "AQA A-Level Chemistry Specification",
        "subject": "Chemistry",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/chemistry/as-and-a-level/chemistry-7404-7405/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-physics-7408",
        "title": "AQA A-Level Physics Specification",
        "subject": "Physics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/physics/as-and-a-level/physics-7407-7408/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-maths-7357",
        "title": "AQA A-Level Mathematics Specification",
        "subject": "Calculus",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/as-and-a-level/mathematics-7357/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-further-maths-7367",
        "title": "AQA A-Level Further Mathematics Specification",
        "subject": "Calculus",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/as-and-a-level/further-mathematics-7367/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-economics-7136",
        "title": "AQA A-Level Economics Specification",
        "subject": "Economics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/economics/as-and-a-level/economics-7135-7136/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-psychology-7182",
        "title": "AQA A-Level Psychology Specification",
        "subject": "Psychology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/psychology/as-and-a-level/psychology-7181-7182/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-computer-science-7517",
        "title": "AQA A-Level Computer Science Specification",
        "subject": "Computer Science",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/computer-science-and-it/as-and-a-level/computer-science-7516-7517/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-history-7042",
        "title": "AQA A-Level History Specification",
        "subject": "History",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/history/as-and-a-level/history-7041-7042/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-geography-7037",
        "title": "AQA A-Level Geography Specification",
        "subject": "Earth Science",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/geography/as-and-a-level/geography-7036-7037/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-sociology-7192",
        "title": "AQA A-Level Sociology Specification",
        "subject": "Sociology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/sociology/as-and-a-level/sociology-7191-7192/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-english-literature-7712",
        "title": "AQA A-Level English Literature Specification",
        "subject": "English",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/as-and-a-level/english-literature-a-7711-7712/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-business-7132",
        "title": "AQA A-Level Business Specification",
        "subject": "Economics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/business/as-and-a-level/business-7131-7132/specification",
        "direct_url": "",
    },
]

# ── BCcampus OpenEd ──────────────────────────────────────────────────────────
# Download URL pattern: https://opentextbc.ca/{slug}/open/download?type=pdf
# All CC-BY 4.0 unless noted. Peer-reviewed Canadian OER collection.

BCCAMPUS_BOOKS: list[dict] = [
    {
        "slug": "bccampus-anatomy-physiology",
        "title": "Anatomy and Physiology (BCcampus)",
        "subject": "Anatomy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/anatomyandphysiology/",
        "direct_url": "https://opentextbc.ca/anatomyandphysiology/open/download?type=pdf",
    },
    {
        "slug": "bccampus-human-biology",
        "title": "Human Biology",
        "subject": "Biology",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/humanbiology/",
        "direct_url": "https://opentextbc.ca/humanbiology/open/download?type=pdf",
    },
    {
        "slug": "bccampus-cell-biology",
        "title": "Cell Biology (BCcampus)",
        "subject": "Biology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/cellbiology/",
        "direct_url": "https://opentextbc.ca/cellbiology/open/download?type=pdf",
    },
    {
        "slug": "bccampus-microbiology",
        "title": "Microbiology (BCcampus)",
        "subject": "Biology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/microbiology/",
        "direct_url": "https://opentextbc.ca/microbiology/open/download?type=pdf",
    },
    {
        "slug": "bccampus-genetics",
        "title": "Genetics (BCcampus)",
        "subject": "Biology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/genetics/",
        "direct_url": "https://opentextbc.ca/genetics/open/download?type=pdf",
    },
    {
        "slug": "bccampus-social-psychology",
        "title": "Social Psychology (BCcampus)",
        "subject": "Psychology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/socialpsychology/",
        "direct_url": "https://opentextbc.ca/socialpsychology/open/download?type=pdf",
    },
    {
        "slug": "bccampus-abnormal-psychology",
        "title": "Abnormal Psychology",
        "subject": "Psychology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://opentextbc.ca/abnormalpsychology/",
        "direct_url": "https://opentextbc.ca/abnormalpsychology/open/download?type=pdf",
    },
    {
        "slug": "bccampus-research-methods-psych",
        "title": "Research Methods in Psychology",
        "subject": "Psychology",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://opentextbc.ca/researchmethods/",
        "direct_url": "https://opentextbc.ca/researchmethods/open/download?type=pdf",
    },
    {
        "slug": "bccampus-physical-geology",
        "title": "Physical Geology 2e",
        "subject": "Earth Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/physicalgeology2ed/",
        "direct_url": "https://opentextbc.ca/physicalgeology2ed/open/download?type=pdf",
    },
    {
        "slug": "bccampus-climate-science",
        "title": "Introduction to Climate Science",
        "subject": "Environmental Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/climatescience/",
        "direct_url": "https://opentextbc.ca/climatescience/open/download?type=pdf",
    },
    {
        "slug": "bccampus-business-comm",
        "title": "Business Communication for Success",
        "subject": "English",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://opentextbc.ca/businesscommunicationatkins/",
        "direct_url": "https://opentextbc.ca/businesscommunicationatkins/open/download?type=pdf",
    },
    {
        "slug": "bccampus-technical-writing",
        "title": "Technical Writing Essentials",
        "subject": "English",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/technicalwriting/",
        "direct_url": "https://opentextbc.ca/technicalwriting/open/download?type=pdf",
    },
    {
        "slug": "bccampus-fundamentals-business",
        "title": "Fundamentals of Business",
        "subject": "Economics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://opentextbc.ca/fundamentalsofbusiness/",
        "direct_url": "https://opentextbc.ca/fundamentalsofbusiness/open/download?type=pdf",
    },
    {
        "slug": "bccampus-project-management",
        "title": "Project Management for Scientists and Engineers",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 3.0",
        "page_url": "https://opentextbc.ca/projectmanagement/",
        "direct_url": "https://opentextbc.ca/projectmanagement/open/download?type=pdf",
    },
    {
        "slug": "bccampus-intro-philosophy",
        "title": "Introduction to Philosophy: Ethics",
        "subject": "Philosophy",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/ethicsopenstax/",
        "direct_url": "https://opentextbc.ca/ethicsopenstax/open/download?type=pdf",
    },
    {
        "slug": "bccampus-environmental-science",
        "title": "Environmental Science (BCcampus)",
        "subject": "Environmental Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/environmentalscience/",
        "direct_url": "https://opentextbc.ca/environmentalscience/open/download?type=pdf",
    },
]

# ── Other Verified OER Sources ────────────────────────────────────────────────

OTHER_OER_BOOKS: list[dict] = [

    # ── Green Tea Press (Allen Downey) — CC-BY-NC ─────────────────────────────
    {
        "slug": "think-complexity-2e",
        "title": "Think Complexity 2e",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / Green Tea Press",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-complexity-2e/",
        "direct_url": "https://greenteapress.com/complexity2/thinkcomplexity2.pdf",
    },
    {
        "slug": "think-bayes",
        "title": "Think Bayes: Bayesian Statistics in Python",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / Green Tea Press",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-bayes/",
        "direct_url": "https://www.greenteapress.com/thinkbayes/thinkbayes.pdf",
    },
    {
        "slug": "think-java-2e",
        "title": "Think Java 2e",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / Green Tea Press",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-java-2e/",
        "direct_url": "https://greenteapress.com/thinkjava2/thinkjava2.pdf",
    },
    {
        "slug": "think-os",
        "title": "Think OS: A Brief Introduction to Operating Systems",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Allen Downey / Green Tea Press",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://greenteapress.com/wp/think-os/",
        "direct_url": "https://www.greenteapress.com/thinkos/thinkos.pdf",
    },

    # ── UBC CLP Calculus Series — CC-BY-NC-SA 4.0 ────────────────────────────
    # University of British Columbia, Department of Mathematics
    {
        "slug": "clp-1-differential-calculus",
        "title": "CLP-1 Differential Calculus",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "UBC Mathematics / CLP",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://personal.math.ubc.ca/~CLP/CLP1/",
        "direct_url": "https://personal.math.ubc.ca/~CLP/CLP1/combined_clp_1.pdf",
    },
    {
        "slug": "clp-2-integral-calculus",
        "title": "CLP-2 Integral Calculus",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "UBC Mathematics / CLP",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://personal.math.ubc.ca/~CLP/CLP2/",
        "direct_url": "https://personal.math.ubc.ca/~CLP/CLP2/combined_clp_2.pdf",
    },
    {
        "slug": "clp-3-multivariable-calculus",
        "title": "CLP-3 Multivariable Calculus",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "UBC Mathematics / CLP",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://personal.math.ubc.ca/~CLP/CLP3/",
        "direct_url": "https://personal.math.ubc.ca/~CLP/CLP3/combined_clp_3.pdf",
    },
    {
        "slug": "clp-4-vector-calculus",
        "title": "CLP-4 Vector Calculus",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "UBC Mathematics / CLP",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://personal.math.ubc.ca/~CLP/CLP4/",
        "direct_url": "https://personal.math.ubc.ca/~CLP/CLP4/combined_clp_4.pdf",
    },

    # ── APEX Calculus — CC-BY-NC 4.0 ─────────────────────────────────────────
    # Gregory Hartman, Virginia Military Institute — canonical HS/college calc
    {
        "slug": "apex-calculus",
        "title": "APEX Calculus (Volumes 1-3)",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "APEX Calculus / Hartman",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://www.apexcalculus.com/",
        "direct_url": "https://opentext.uleth.ca/PDF/APEX-1565-colour.pdf",
    },

    # ── OpenIntro — CC-BY-SA 4.0 ──────────────────────────────────────────────
    {
        "slug": "openintro-statistics",
        "title": "OpenIntro Statistics 4e",
        "subject": "Statistics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenIntro",
        "license": "CC-BY-SA 4.0",
        "page_url": "https://www.openintro.org/book/os/",
        "direct_url": "https://www.openintro.org/book/stat/openintro-statistics.pdf",
    },
    {
        "slug": "openintro-intro-stat-randomization",
        "title": "Introduction to Statistics with Randomization and Simulation",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "OpenIntro",
        "license": "CC-BY-SA 4.0",
        "page_url": "https://www.openintro.org/book/isrs/",
        "direct_url": "https://www.openintro.org/book/isrs/openintro_stat_simulations.pdf",
    },

    # ── MIT OpenCourseWare — CC-BY-NC-SA 4.0 ─────────────────────────────────
    {
        "slug": "mit-math-for-cs",
        "title": "Mathematics for Computer Science (MIT 6.042J)",
        "subject": "Mathematics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "MIT OpenCourseWare",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/",
        "direct_url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/mit6_042js15_textbook.pdf",
    },

    # ── Abstract Algebra (Judson) — GFDL ─────────────────────────────────────
    {
        "slug": "abstract-algebra-judson",
        "title": "Abstract Algebra: Theory and Applications",
        "subject": "Mathematics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Tom Judson / Abstract Algebra",
        "license": "GFDL",
        "page_url": "http://abstract.ups.edu/",
        "direct_url": "http://abstract.ups.edu/download/aata-20230201.pdf",
    },

    # ── Real Analysis (Trench) — CC-BY-NC-SA ─────────────────────────────────
    {
        "slug": "real-analysis-trench",
        "title": "Introduction to Real Analysis",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "William Trench / CC-BY-NC-SA",
        "license": "CC-BY-NC-SA",
        "page_url": "https://ramanujan.math.trinity.edu/wtrench/misc/index.shtml",
        "direct_url": "https://ramanujan.math.trinity.edu/wtrench/texts/TRENCH_REAL_ANALYSIS.PDF",
    },

    # ── LibreTexts batch PDFs ─────────────────────────────────────────────────
    # IDs verified via LibreTexts batch print system (batch.libretexts.org)
    {
        "slug": "libretexts-physics-general",
        "title": "General Physics (UC Davis, LibreTexts)",
        "subject": "Physics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "LibreTexts / UC Davis",
        "license": "CC-BY 4.0",
        "page_url": "https://phys.libretexts.org/Courses/University_of_California_Davis/UCD%3A_Physics_7A_-_General_Physics",
        "direct_url": "https://batch.libretexts.org/print/Letter/Finished/phys-1989/Full.pdf",
    },
    {
        "slug": "libretexts-chem-biological",
        "title": "Chemistry with Biological Emphasis (LibreTexts)",
        "subject": "Chemistry",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "LibreTexts",
        "license": "CC-BY-NC-SA 4.0",
        "page_url": "https://chem.libretexts.org/Courses/Chabot_College/Chem_12A",
        "direct_url": "https://batch.libretexts.org/print/Letter/Finished/chem-402216/Full.pdf",
    },

    # ── Active Calculus (Matt Boelkins, GVSU) — CC-BY-SA 4.0 ─────────────────
    {
        "slug": "active-calculus-single",
        "title": "Active Calculus: Single Variable",
        "subject": "Calculus",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Matt Boelkins / GVSU",
        "license": "CC-BY-SA 4.0",
        "page_url": "https://activecalculus.org/single/",
        "direct_url": "https://scholarworks.gvsu.edu/cgi/viewcontent.cgi?article=1034&context=books",
    },

    # ── Combinatorics (Bogart, Dartmouth) — CC-BY-SA ─────────────────────────
    {
        "slug": "combinatorics-bogart",
        "title": "Combinatorics Through Guided Discovery",
        "subject": "Mathematics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Kenneth Bogart / Dartmouth",
        "license": "CC-BY-SA",
        "page_url": "https://math.dartmouth.edu/news-resources/electronic/kpbogart/",
        "direct_url": "https://math.dartmouth.edu/news-resources/electronic/kpbogart/combinatorics2017_2_28.pdf",
    },

    # ── SICP (MIT) — CC-BY-SA 4.0 ────────────────────────────────────────────
    {
        "slug": "sicp",
        "title": "Structure and Interpretation of Computer Programs 2e",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "MIT Press / CC-BY-SA",
        "license": "CC-BY-SA 4.0",
        "page_url": "https://mitp-content-server.mit.edu/books/content/sectbyfn/books_pres_0/6515/sicp.zip/index.html",
        "direct_url": "https://web.mit.edu/alexmv/6.037/sicp.pdf",
    },

    # ── Eloquent JavaScript (Haverbeke) — CC-BY-NC ───────────────────────────
    {
        "slug": "eloquent-javascript",
        "title": "Eloquent JavaScript 3e",
        "subject": "Computer Science",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Marijn Haverbeke / CC-BY-NC",
        "license": "CC-BY-NC 4.0",
        "page_url": "https://eloquentjavascript.net/",
        "direct_url": "https://eloquentjavascript.net/Eloquent_JavaScript.pdf",
    },

    # ── AP-level US curriculum extras ─────────────────────────────────────────
    # Stitz-Zeager Precalculus (supplement to OpenStax Precalc)
    {
        "slug": "stitz-zeager-precalculus",
        "title": "Precalculus (Stitz-Zeager)",
        "subject": "Pre-Calculus",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Stitz-Zeager Open Source Mathematics",
        "license": "CC-BY-NC-SA 3.0",
        "page_url": "http://www.stitz-zeager.com/",
        "direct_url": "http://www.stitz-zeager.com/szprecalculus07042013.pdf",
    },

    # ── AP Statistics / Probability ───────────────────────────────────────────
    {
        "slug": "introduction-probability-blitzstein",
        "title": "Introduction to Probability (Blitzstein & Hwang)",
        "subject": "Statistics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Harvard / Chapman & Hall — Free PDF",
        "license": "Free for non-commercial use",
        "page_url": "https://projects.iq.harvard.edu/stat110/home",
        "direct_url": "https://drive.google.com/uc?export=download&id=1VmkAAGOYCTORq1wxSQqy255qLJjTNvBI",
    },

    # ── Internet Archive mirrors — public domain / CC ─────────────────────────
    {
        "slug": "ck12-biology-hs",
        "title": "CK-12 Biology for High School",
        "subject": "Biology",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "CK-12 Foundation / Internet Archive",
        "license": "CC-BY-NC 3.0",
        "page_url": "https://archive.org/details/CK12BiologyFlexbook20",
        "direct_url": "https://archive.org/download/CK12BiologyFlexbook20/ck12_biology_flexbook_2.0.pdf",
    },
    {
        "slug": "ck12-chemistry-hs",
        "title": "CK-12 Chemistry for High School",
        "subject": "Chemistry",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "CK-12 Foundation / Internet Archive",
        "license": "CC-BY-NC 3.0",
        "page_url": "https://archive.org/details/CK12ChemistrySecondEdition",
        "direct_url": "https://archive.org/download/CK12ChemistrySecondEdition/CK12-Chemistry-Full.pdf",
    },
    {
        "slug": "ck12-earth-science",
        "title": "CK-12 Earth Science for Middle School",
        "subject": "Earth Science",
        "grade_level": "Grade 6-8",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "CK-12 Foundation / Internet Archive",
        "license": "CC-BY-NC 3.0",
        "page_url": "https://archive.org/details/ck12-earth-science",
        "direct_url": "https://archive.org/download/ck12-earth-science/ck12-earth-science.pdf",
    },
    {
        "slug": "ck12-physics-hs",
        "title": "CK-12 Physics for High School",
        "subject": "Physics",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "CK-12 Foundation / Internet Archive",
        "license": "CC-BY-NC 3.0",
        "page_url": "https://archive.org/details/ck12-physics",
        "direct_url": "https://archive.org/download/ck12-physics/ck12-physics.pdf",
    },

    # ── Environmental Science ─────────────────────────────────────────────────
    {
        "slug": "environmental-science-openintro",
        "title": "Environmental Science: A Study of Interrelationships",
        "subject": "Environmental Science",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / CC",
        "license": "Free for educational use",
        "page_url": "https://archive.org/details/environmentalscience",
        "direct_url": "https://archive.org/download/environmentalscience/EnvironmentalScience.pdf",
    },

    # ── Number Theory ─────────────────────────────────────────────────────────
    {
        "slug": "elementary-number-theory-stein",
        "title": "Elementary Number Theory (Stein)",
        "subject": "Mathematics",
        "grade_level": "College",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "William Stein / Free",
        "license": "Free for non-commercial use",
        "page_url": "https://wstein.org/ent/",
        "direct_url": "https://wstein.org/ent/ent.pdf",
    },
]

ALL_SOURCES: list[dict] = (
    OPENSTAX_BOOKS
    + AQA_GCSE_RESOURCES
    + AQA_ALEVEL_RESOURCES
    + BCCAMPUS_BOOKS
    + OTHER_OER_BOOKS
)

SOURCE_FILTER: dict[str, list[dict]] = {
    "openstax": OPENSTAX_BOOKS,
    "gcse": AQA_GCSE_RESOURCES,
    "alevel": AQA_ALEVEL_RESOURCES,
    "uk": AQA_GCSE_RESOURCES + AQA_ALEVEL_RESOURCES,
    "us": OPENSTAX_BOOKS,
    "bccampus": BCCAMPUS_BOOKS,
    "oer": OTHER_OER_BOOKS,
    "all": ALL_SOURCES,
}
