"""
Curriculum resource catalog for overnight ingestion.

Each entry describes one document to download and ingest into hs_curriculum.
Fields:
  slug/title   — identifier used to construct download URL or log progress
  subject      — canonical subject name (must match context_store._SUBJECT_ALIASES)
  grade_level  — "GCSE", "A-Level", "AP", "Grade 9-12", etc.
  curriculum   — "us" | "uk"
  source_type  — "openstax" | "gcse_aqa" | "gcse_edexcel" | "libretexts" | "direct"
  source_name  — human-readable source label
  license      — license string
  page_url     — the human-readable page (used to scrape or as reference)
  direct_url   — direct PDF download URL (leave "" if not known; downloader will resolve)

Adding entries:
  1. For OpenStax: provide slug only. Downloader fetches the PDF URL via OpenStax API.
  2. For AQA: provide page_url. Downloader scrapes the spec PDF link from the page.
  3. For direct: provide direct_url. Downloader downloads it directly.
"""

OPENSTAX_BOOKS: list[dict] = [
    {
        "slug": "biology-2e",
        "title": "Biology 2e",
        "subject": "Biology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/biology-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Biology2e-WEB.pdf",
    },
    {
        "slug": "chemistry-2e",
        "title": "Chemistry 2e",
        "subject": "Chemistry",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/chemistry-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Chemistry2e-WEB.pdf",
    },
    {
        "slug": "college-algebra-2e",
        "title": "College Algebra 2e",
        "subject": "Algebra",
        "grade_level": "Grade 9-12",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Stitz-Zeager Open Source Mathematics",
        "license": "CC-BY-NC-SA 3.0",
        "page_url": "http://www.stitz-zeager.com/college_algebra.html",
        "direct_url": "http://www.stitz-zeager.com/szca07042013.pdf",
    },
    {
        "slug": "algebra-and-trigonometry-2e",
        "title": "Algebra and Trigonometry 2e",
        "subject": "Algebra",
        "grade_level": "Grade 10-12",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/algebra-and-trigonometry-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/AlgebraAndTrigonometry2e-WEB.pdf",
    },
    {
        "slug": "precalculus-2e",
        "title": "Precalculus 2e",
        "subject": "Pre-Calculus",
        "grade_level": "Grade 11-12",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/precalculus-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Precalculus_2e-WEB.pdf",
    },
    {
        "slug": "calculus-volume-1",
        "title": "Calculus Volume 1",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://archive.org/details/calculus-volume-1",
        "direct_url": "https://archive.org/download/calculus-volume-1/Calculus%2C%20Volume%201.pdf",
    },
    {
        "slug": "calculus-volume-2",
        "title": "Calculus Volume 2",
        "subject": "Calculus",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "Internet Archive / OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://archive.org/details/calculus-volume-2-web",
        "direct_url": "https://archive.org/download/calculus-volume-2-web/Calculus_Volume_2_-_WEB.pdf",
    },
    {
        "slug": "introductory-statistics",
        "title": "Introductory Statistics",
        "subject": "Statistics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/introductory-statistics",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/Statistics-WEB.pdf",
    },
    {
        "slug": "us-history",
        "title": "U.S. History",
        "subject": "US History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/us-history",
        "direct_url": "",
    },
    {
        "slug": "world-history-volume-1",
        "title": "World History Volume 1",
        "subject": "World History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/world-history-volume-1",
        "direct_url": "",
    },
    {
        "slug": "world-history-volume-2",
        "title": "World History Volume 2",
        "subject": "World History",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/world-history-volume-2",
        "direct_url": "",
    },
    {
        "slug": "psychology-2e",
        "title": "Introduction to Psychology",
        "subject": "Psychology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/introductiontopsychology/",
        "direct_url": "https://opentextbc.ca/introductiontopsychology/open/download?type=pdf",
    },
    {
        "slug": "sociology-3e",
        "title": "Introduction to Sociology",
        "subject": "Sociology",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "direct",
        "source_name": "BCcampus OpenEd",
        "license": "CC-BY 4.0",
        "page_url": "https://opentextbc.ca/introductiontosociology2ndedition/",
        "direct_url": "https://opentextbc.ca/introductiontosociology2ndedition/open/download?type=pdf",
    },
    {
        "slug": "principles-economics-3e",
        "title": "Principles of Economics 3e",
        "subject": "Economics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/principles-economics-3e",
        "direct_url": "",
    },
    {
        "slug": "anatomy-and-physiology",
        "title": "Anatomy and Physiology",
        "subject": "Anatomy",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/anatomy-and-physiology",
        "direct_url": "",
    },
    {
        "slug": "college-physics-2e",
        "title": "College Physics 2e",
        "subject": "Physics",
        "grade_level": "AP",
        "curriculum": "us",
        "source_type": "openstax",
        "source_name": "OpenStax",
        "license": "CC-BY 4.0",
        "page_url": "https://openstax.org/details/books/college-physics-2e",
        "direct_url": "https://assets.openstax.org/oscms-prodcms/media/documents/College_Physics_2e-WEB.pdf",
    },
]

AQA_GCSE_RESOURCES: list[dict] = [
    {
        "slug": "aqa-gcse-biology-8461",
        "title": "AQA GCSE Biology Specification",
        "subject": "Biology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/biology/gcse/biology-8461/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-chemistry-8462",
        "title": "AQA GCSE Chemistry Specification",
        "subject": "Chemistry",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/chemistry/gcse/chemistry-8462/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-physics-8463",
        "title": "AQA GCSE Physics Specification",
        "subject": "Physics",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/physics/gcse/physics-8463/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-maths-8300",
        "title": "AQA GCSE Mathematics Specification",
        "subject": "Algebra",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-english-language-8700",
        "title": "AQA GCSE English Language Specification",
        "subject": "English",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/english/gcse/english-language-8700/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-geography-8035",
        "title": "AQA GCSE Geography Specification",
        "subject": "Earth Science",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-history-8145",
        "title": "AQA GCSE History Specification",
        "subject": "History",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/history/gcse/history-8145/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-economics-8136",
        "title": "AQA GCSE Economics Specification",
        "subject": "Economics",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/economics/gcse/economics-8136/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-gcse-psychology-8182",
        "title": "AQA GCSE Psychology Specification",
        "subject": "Psychology",
        "grade_level": "GCSE",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/psychology/gcse/psychology-8182/specification",
        "direct_url": "",
    },
]

AQA_ALEVEL_RESOURCES: list[dict] = [
    {
        "slug": "aqa-alevel-biology-7402",
        "title": "AQA A-Level Biology Specification",
        "subject": "Biology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/biology/as-and-a-level/biology-7401-7402/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-chemistry-7405",
        "title": "AQA A-Level Chemistry Specification",
        "subject": "Chemistry",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/chemistry/as-and-a-level/chemistry-7404-7405/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-physics-7408",
        "title": "AQA A-Level Physics Specification",
        "subject": "Physics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/physics/as-and-a-level/physics-7407-7408/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-maths-7357",
        "title": "AQA A-Level Mathematics Specification",
        "subject": "Calculus",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/mathematics/as-and-a-level/mathematics-7357/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-economics-7136",
        "title": "AQA A-Level Economics Specification",
        "subject": "Economics",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/economics/as-and-a-level/economics-7135-7136/specification",
        "direct_url": "",
    },
    {
        "slug": "aqa-alevel-psychology-7182",
        "title": "AQA A-Level Psychology Specification",
        "subject": "Psychology",
        "grade_level": "A-Level",
        "curriculum": "uk",
        "source_type": "gcse_aqa",
        "source_name": "AQA",
        "license": "Free for educational use",
        "page_url": "https://www.aqa.org.uk/subjects/psychology/as-and-a-level/psychology-7181-7182/specification",
        "direct_url": "",
    },
]

ALL_SOURCES: list[dict] = OPENSTAX_BOOKS + AQA_GCSE_RESOURCES + AQA_ALEVEL_RESOURCES

SOURCE_FILTER: dict[str, list[dict]] = {
    "openstax": OPENSTAX_BOOKS,
    "gcse": AQA_GCSE_RESOURCES,
    "alevel": AQA_ALEVEL_RESOURCES,
    "uk": AQA_GCSE_RESOURCES + AQA_ALEVEL_RESOURCES,
    "us": OPENSTAX_BOOKS,
    "all": ALL_SOURCES,
}
