import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { 
  Play, Brain, Sparkles, Loader, AlertCircle, BarChart3,
  BookOpen, Gauge, Cpu, Database, ArrowRight
} from 'lucide-react';
import './SoloQuiz.css';
import quizAgentService from '../services/quizAgentService';

const SoloQuiz = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const username = localStorage.getItem('username');
  
  const [subject, setSubject] = useState('');
  const [difficulty, setDifficulty] = useState('medium');
  const [questionCount, setQuestionCount] = useState(10);
  const [questionTypes] = useState(['multiple_choice']);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [useAdaptive, setUseAdaptive] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const getDifficultyMix = () => {
    switch (difficulty) {
      case 'easy': return { easy: 6, medium: 3, hard: 1 };
      case 'medium': return { easy: 3, medium: 5, hard: 2 };
      case 'hard': return { easy: 1, medium: 4, hard: 5 };
      default: return { easy: 3, medium: 5, hard: 2 };
    }
  };

  useEffect(() => {
    const autoStartData = location.state;
    if (autoStartData?.autoStart && autoStartData.topics?.length > 0) {
      setSubject(autoStartData.topics[0]);
      setDifficulty(autoStartData.difficulty || 'medium');
      setQuestionCount(autoStartData.questionCount || 10);
      setTimeout(() => {
        handleStartQuiz(null, autoStartData.topics[0], autoStartData.difficulty || 'medium', autoStartData.questionCount || 10);
      }, 500);
      window.history.replaceState({}, document.title);
    }
  }, [location.state]);

  const handleStartQuiz = async (e, autoTopic = null, autoDifficulty = null, autoCount = null) => {
    if (e) e.preventDefault();
    const topicToUse = autoTopic || subject;
    const difficultyToUse = autoDifficulty || difficulty;
    const countToUse = autoCount || questionCount;
    
    if (!topicToUse) {
      setError('Please enter a subject to begin your quiz');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      let response;
      if (useAdaptive) {
        response = await quizAgentService.generateAdaptiveQuiz({
          userId: username,
          topic: topicToUse,
          questionCount: countToUse
        });
      } else {
        response = await quizAgentService.generateQuiz({
          userId: username,
          topic: topicToUse,
          questionCount: countToUse,
          difficultyMix: getDifficultyMix(),
          questionTypes
        });
      }

      if (response.success && response.questions?.length > 0) {
        sessionStorage.setItem('quizData', JSON.stringify({
          questions: response.questions,
          topic: topicToUse,
          difficulty: difficultyToUse,
          adaptiveConfig: response.adaptive_config
        }));
        navigate('/solo-quiz/session');
      } else {
        setError('Unable to generate questions. Please try a different topic.');
      }
    } catch (err) {
      setError(err.message || 'Failed to create quiz. Please try again.');
    } finally {
      setLoading(false);
      setShowCreateModal(false);
    }
  };

  return (
    <div className="sq-page">
      <header className="sq-header">
        <div className="sq-header-left">
          <h1 className="sq-logo" onClick={() => navigate('/dashboard')}>cerbyl</h1>
          <div className="sq-header-divider"></div>
          <span className="sq-subtitle">AI QUIZ</span>
        </div>
        <div className="sq-header-right">
          <button className="sq-nav-btn" onClick={() => navigate('/quiz-hub')}>
            <BarChart3 size={16} />
            Quiz Hub
          </button>
          <button className="sq-nav-btn" onClick={() => navigate('/dashboard')}>
            Dashboard
          </button>
        </div>
      </header>

      <div className="sq-content">
        <div className="sq-welcome">
          <div className="sq-welcome-inner">
            <Brain size={56} className="sq-icon" />
            <h2 className="sq-title">
              <span className="sq-title-gradient">AI-Powered</span> Quiz
            </h2>
            <p className="sq-desc">
              Challenge yourself with intelligent quizzes generated by AI. 
              Get personalized questions that adapt to your learning journey.
            </p>
          </div>
          <button className="sq-start-btn" onClick={() => setShowCreateModal(true)}>
            <Sparkles size={22} />
            <span>Start New Quiz</span>
          </button>
        </div>

        {error && (
          <div className="sq-error">
            <AlertCircle size={22} />
            <span>{error}</span>
            <button onClick={() => setError(null)}>×</button>
          </div>
        )}
      </div>

      {showCreateModal && (
        <div className="sq-modal-overlay" onClick={() => setShowCreateModal(false)}>
          <div className="sq-modal" onClick={(e) => e.stopPropagation()}>
            <div className="sq-modal-header">
              <h3><Brain size={22} /> Create AI Quiz</h3>
              <button className="sq-modal-close" onClick={() => setShowCreateModal(false)}>×</button>
            </div>

            <form onSubmit={handleStartQuiz} className="sq-form">
              <div className="sq-form-group">
                <label>
                  <BookOpen size={14} />
                  Subject / Topic
                </label>
                <input
                  type="text"
                  value={subject}
                  onChange={(e) => setSubject(e.target.value)}
                  placeholder="e.g., Machine Learning, World War II, Calculus..."
                  required
                />
              </div>

              <div className="sq-form-row">
                <div className="sq-form-group">
                  <label>
                    <Gauge size={14} />
                    Difficulty
                  </label>
                  <select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}>
                    <option value="easy">Easy</option>
                    <option value="medium">Medium</option>
                    <option value="hard">Hard</option>
                  </select>
                </div>

                <div className="sq-form-group">
                  <label>
                    <Database size={14} />
                    Questions
                  </label>
                  <input
                    type="number"
                    value={questionCount}
                    onChange={(e) => setQuestionCount(Math.min(20, Math.max(5, parseInt(e.target.value) || 5)))}
                    min="5"
                    max="20"
                  />
                </div>
              </div>

              <div className="sq-form-group sq-adaptive-toggle">
                <label className="sq-toggle-label">
                  <input
                    type="checkbox"
                    checked={useAdaptive}
                    onChange={(e) => setUseAdaptive(e.target.checked)}
                  />
                  <span className="sq-toggle-text">
                    <Cpu size={18} />
                    Use Adaptive Mode
                  </span>
                </label>
                <p className="sq-toggle-desc">AI adjusts questions based on your past performance</p>
              </div>

              <button type="submit" className="sq-submit-btn" disabled={loading}>
                {loading ? (
                  <>
                    <Loader size={18} className="spinner" />
                    <span>Generating...</span>
                  </>
                ) : (
                  <>
                    <Play size={18} />
                    <span>Start Quiz</span>
                  </>
                )}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default SoloQuiz;
